name: roomates
description: roomates for roommates.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.10
  firebase_core: ^2.8.0
  google_sign_in: ^6.0.2
  cloud_firestore: ^4.4.5
  firebase_database: ^10.0.16
  table_calendar: ^3.0.8
  image_picker: ^0.8.7+1
  firebase_storage: ^11.1.0
  intl: ^0.17.0
  flutter_local_notifications: ^13.0.0
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Alkatra
      fonts:
        - asset: lib/fonts/Alkatra-Regular.ttf
  assets:
    - assets/images/facebook.png
    - assets/images/google-symbol.png
    - assets/images/default_avatar.png
  uses-material-design: true
  