// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFrRH7oROiU1VrK-RvG3JIRRzSuRtmvQU',
    appId: '1:650089109617:web:78055dbfef5ad5409d23d0',
    messagingSenderId: '650089109617',
    projectId: 'roomates-52b99',
    authDomain: 'roomates-52b99.firebaseapp.com',
    storageBucket: 'roomates-52b99.appspot.com',
    measurementId: 'G-7W89DL3S4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDBi6ruKo-06_RANv2MnMFVa-bRG8Q2hA',
    appId: '1:650089109617:android:e52f5f14205ddf659d23d0',
    messagingSenderId: '650089109617',
    projectId: 'roomates-52b99',
    storageBucket: 'roomates-52b99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEl6fkG2jxuOSGEicNJka8hoeEj78G-gg',
    appId: '1:650089109617:ios:b6140517f85bee879d23d0',
    messagingSenderId: '650089109617',
    projectId: 'roomates-52b99',
    storageBucket: 'roomates-52b99.appspot.com',
    iosClientId: '650089109617-o3cja2n0dt0aog6ctls0v98jfpk2ui5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEl6fkG2jxuOSGEicNJka8hoeEj78G-gg',
    appId: '1:650089109617:ios:b6140517f85bee879d23d0',
    messagingSenderId: '650089109617',
    projectId: 'roomates-52b99',
    storageBucket: 'roomates-52b99.appspot.com',
    iosClientId: '650089109617-o3cja2n0dt0aog6ctls0v98jfpk2ui5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomates',
  );
}
