// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMHJmLgJOj8NXnsVQ2twU91KVynqelWWo',
    appId: '1:24536231275:web:b96632363c7c009d7ff02e',
    messagingSenderId: '24536231275',
    projectId: 'roomates-7d171',
    authDomain: 'roomates-7d171.firebaseapp.com',
    storageBucket: 'roomates-7d171.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyrkhGpkerhPuIRcapP8i9o_F-UUoA3DA',
    appId: '1:24536231275:android:f4431f0224db57157ff02e',
    messagingSenderId: '24536231275',
    projectId: 'roomates-7d171',
    storageBucket: 'roomates-7d171.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_1rZ0-cNO3v7hU1NV6KcQy5DW78PVgzA',
    appId: '1:24536231275:ios:4c40fc8654b6253a7ff02e',
    messagingSenderId: '24536231275',
    projectId: 'roomates-7d171',
    storageBucket: 'roomates-7d171.appspot.com',
    iosClientId: '24536231275-co72uql7ah7t41akk0bplevqf9g236al.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_1rZ0-cNO3v7hU1NV6KcQy5DW78PVgzA',
    appId: '1:24536231275:ios:4c40fc8654b6253a7ff02e',
    messagingSenderId: '24536231275',
    projectId: 'roomates-7d171',
    storageBucket: 'roomates-7d171.appspot.com',
    iosClientId: '24536231275-co72uql7ah7t41akk0bplevqf9g236al.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomates',
  );
}
